### ISSUE TITLE
ImportError: cannot import name Faker

### ISSUE THREAD

**Issue by BrendanBerkley** [joke2k/django-faker#10]
I did a fresh install and was actually able to generate some Users, but then after trying to run a python script outside of the console, something went wrong and it doesn't work again. This error message isn't very helpful to me :frowning: 

Any ideas? I tried uninstalling and reinstalling and doing exactly what I did to make it work before, but still got the following. 

```
Python 2.7.5+ (default, Feb 27 2014, 19:37:08) 
[GCC 4.8.1] on linux2
>>> from django_faker import Faker
>>> populator = Faker.getPopulator()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django_faker/__init__.py", line 90, in getPopulator
    generator = cls.generators.get(codename,  None) or cls.getGenerator(codename=codename)
  File "/usr/local/lib/python2.7/dist-packages/django_faker/__init__.py", line 54, in getGenerator
    from faker import Faker as FakerGenerator
ImportError: cannot import name Faker
```

**Comment by jargnar** [comment]
+1, I get this on a Windows 10 machine with Anaconda after I `pip install fake-factory`.

```
>>> from faker import Faker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "faker.py", line 5, in <module>
    from faker import Faker
ImportError: cannot import name Faker
>>> from faker import Factory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "faker.py", line 5, in <module>
    from faker import Faker
ImportError: cannot import name Faker
>>>

c:\lab>pip install fake-factory
You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): fake-factory in c:\app\anaconda\lib\site-packages
```

**Comment by officialrahulmandal** [comment]
Hey @BrendanBerkley ,
Why don't you use Faker library which is there on pypi.org. it's really cool and have a good documentation.
Happy coding :-)
