### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'phoneNumber'

### ISSUE THREAD

**Issue by show0k** [joke2k/django-faker#12]
I've a custom User model with a field 
phone_number = models.CharField( max_length=20)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/dev/local/lib/python2.7/site-packages/django_faker/populator.py", line 163, in execute
    insertedEntities[klass].append( self.entities[klass].execute(using, insertedEntities) )
  File "/dev/local/lib/python2.7/site-packages/django_faker/populator.py", line 104, in execute
    value = format(insertedEntities) if hasattr(format,'**call**') else format
  File "/dev/local/lib/python2.7/site-packages/django_faker/guessers.py", line 25, in <lambda>
    if name in ('phone_number','phonenumber','phone'): return lambda x:generator.phoneNumber()
AttributeError: 'Generator' object has no attribute 'phoneNumber'

**Comment by Brobin** [comment]
Issue with faker's API changing. It should be `return lambda x: generator.phone_number()`
