### ISSUE TITLE
For foreignkey fields get error with 'rel' attribute

### ISSUE THREAD

**Issue by clikman007** [joke2k/django-faker#27]
populator.addEntity(Patient, 2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/user/www/virt_env/lib/python3.5/site-packages/django_faker/populator.py", line 138, in addEntity
    model.fieldFormatters = model.guessFieldFormatters( self.generator )
  File "/home/user/www/virt_env/lib/python3.5/site-packages/django_faker/populator.py", line 65, in guessFieldFormatters
    relatedModel = field.rel.to
AttributeError: 'ForeignKey' object has no attribute 'rel'

**Comment by david-wizzili** [comment]
I've fixed this in a separate branch for now (https://github.com/david-wizzili/django-faker)

@joke2k , please feel free to pull what's there if it's OK with you.
