### ISSUE TITLE
fake-factory update: Faker

### ISSUE THREAD

**Issue by anx-abruckner** [joke2k/django-faker#30]
When trying to initiate the faker (via `populator = Faker.getPopulator()`) it fails:

```
ImportError: The ``fake-factory`` package is now called ``Faker``.
Please update your requirements.
```

Any idea when this update might be done? =)

Complete Traceback (most recent call last):
```
File "/opt/project/app/manage.py", line 22, in <module>
  execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
  utility.execute()
File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 356, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
  self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
  output = self.handle(*args, **options)
File "/opt/project/app/myapp/package/management/commands/usefaker.py", line 17, in handle
  populator = Faker.getPopulator()
File "/usr/local/lib/python3.4/site-packages/django_faker/__init__.py", line 90, in getPopulator
  generator = cls.generators.get(codename,  None) or cls.getGenerator(codename=codename)
File "/usr/local/lib/python3.4/site-packages/django_faker/__init__.py", line 54, in getGenerator
  from faker import Faker as FakerGenerator
File "/usr/local/lib/python3.4/site-packages/faker/__init__.py", line 7, in <module>
  raise ImportError(error)
ImportError: The ``fake-factory`` package is now called ``Faker``.

Please update your requirements.
```

**Comment by SolarLiner** [comment]
Hi! I've had this problem too and decided to fork it under another name. Check out [Django Populate](https://gitlab.com/solarliner/django-populate), and `pip install django-populate`.
