### ISSUE TITLE
Faker.getPopulator() raising an AttributeError

### ISSUE THREAD

**Issue by joshainglis** [joke2k/django-faker#9]
Hi, I've just installed django-faker and upon first attempt, this occurred:

```
>>> from django_faker import Faker
>>> populator = Faker.getPopulator()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/sadb/local/lib/python2.7/site-packages/django_faker/__init__.py", line 90, in getPopulator
    generator = cls.generators.get(codename,  None) or cls.getGenerator(codename=codename)
  File "/home/vagrant/.virtualenvs/sadb/local/lib/python2.7/site-packages/django_faker/__init__.py", line 58, in getGenerator
    cls.generators[codename].seed( cls.generators[codename].randomInt() )
AttributeError: 'Generator' object has no attribute 'randomInt'
```

**Comment by edwinlunando** [comment]
Hi, I got this errors too. Do you mind releasing a new fix to pypi? Thanks

**Comment by sametmax** [comment]
+1
